import { useState } from 'react'
import { importPreview, makeBackup, utcDay, validateBackup, type Backup, type Snapshot } from '../../shared/model'
import { engine, type AppState } from '../data/store'
import type { InstallEvent } from '../pwa'
import Icon from './Icon'

function download(text:string,name:string,mime:string){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function Settings({state,install,onDone,onLogin}:{state:AppState;install:InstallEvent|null;onDone:(message:string)=>void;onLogin:()=>void}){
  const [backup,setBackup]=useState<Backup|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),snapshot=state.snapshot
  const preview=snapshot&&backup?importPreview(snapshot,backup):null
  async function read(file:File|undefined){if(!file)return;setError('');setBackup(null);try{if(file.size>12_000_000)throw new Error('Choose a JSON backup smaller than 12 MB.');setBackup(validateBackup(JSON.parse(await file.text()),utcDay()))}catch(e){setError(e instanceof Error?e.message:'This backup is not valid.')}}
  function exportFile(format:'json'|'csv'){
    if(!snapshot)return;setError('')
    try{if(format==='json')download(JSON.stringify(makeBackup(snapshot),null,2),`vigil-${utcDay()}.json`,'application/json');else{const fields=['id','date','loggedAt','createdAt','updatedAt','easy','external','version','deleted','backdated'] as const;download([fields.join(','),...snapshot.entries.map(e=>fields.map(k=>JSON.stringify(e[k])).join(','))].join('\r\n'),`vigil-${utcDay()}.csv`,'text/csv;charset=utf-8')}}catch{setError('This download could not be created. Your records remain retained.')}
  }
  async function importFile(){if(!preview||!backup||busy)return;setBusy(true);setError('');try{await engine.importItems(preview.items,backup.trackingStart);onDone('Backup merged. Identical records were skipped; conflicting records were kept unchanged.')}catch(e){setError(e instanceof Error?e.message:'Import could not be retained.')}finally{setBusy(false)}}
  return <div className="settings-content">
    <section><h3>Make it your daily window</h3><p>Vigil works in a browser and as an installed app with its own window.</p>{install?<button className="primary-button" onClick={()=>{void install.prompt().catch(()=>setError('Open Vigil directly in your browser to install it.'))}}>Install Vigil</button>:<p className="install-note"><strong>Safari on Mac</strong> · Share → Add to Dock.<br/><strong>Chrome</strong> · Use the install icon in the address bar, or the app menu’s install option when offered.</p>}<p className="fine-print">Open the live website in Safari or Chrome for installation. Compact view can be bookmarked at /compact.</p></section>
    <section><h3>Back up your applications</h3><p>JSON keeps entries, UTC dates, goal history, and your tracking start. CSV is useful for reviewing entry records.</p><div className="settings-actions"><button disabled={!snapshot} onClick={()=>exportFile('json')}><Icon name="download"/>JSON backup</button><button disabled={!snapshot} onClick={()=>exportFile('csv')}><Icon name="download"/>CSV entries</button></div>{state.queue.length>0&&<p className="fine-print">Downloads include {state.queue.length} retained pending changes. Sync first for a cloud-confirmed backup.</p>}</section>
    <section><h3>Restore a JSON backup</h3><p>Missing IDs are added. Identical records are skipped. Conflicting records and goals keep their current values.</p><label className="file-label">Choose a Vigil backup<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{void read(e.target.files?.[0])}}/></label>{preview&&backup&&<div className="import-preview"><div><strong>{preview.items.length}</strong> new records <span>· {preview.duplicates} identical · {preview.conflicts.length} conflicts skipped</span></div>{backup.trackingStart<(snapshot as Snapshot).trackingStart&&<p>Tracking start moves to {backup.trackingStart} UTC.</p>}{preview.conflicts.length>0&&<details><summary>Review skipped conflicts</summary><ul>{preview.conflicts.slice(0,50).map((x,i)=><li key={i}>{x}</li>)}</ul>{preview.conflicts.length>50&&<p>And {preview.conflicts.length-50} more.</p>}</details>}<button className="primary-button" disabled={busy||(!preview.items.length&&backup.trackingStart>=(snapshot as Snapshot).trackingStart)} onClick={()=>{void importFile()}}><Icon name="upload"/>{busy?'Retaining import…':'Merge missing records'}</button></div>}</section>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <section><h3>Owner session</h3><p>Remembered for up to 90 days. Cached records stay on this trusted device; cloud writes require a valid session.</p>{state.status==='auth'?<button onClick={onLogin}>Sign in to sync</button>:<button disabled={busy||state.queue.length>0} onClick={()=>{setBusy(true);void engine.logout().then(()=>onLogin()).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}><Icon name="logout"/>Sign out</button>}{state.queue.length>0&&<p className="fine-print">Finish syncing pending changes before signing out.</p>}</section>
    <footer className="about"><img src="/mark.svg" alt=""/><div><strong>Vigil <span>1.0.0</span></strong><p>Independent personal job-application tracker.<br/>UTC days · One owner · No automatic applications.</p></div></footer>
  </div>
}
