import { useEffect, useRef, useState, useSyncExternalStore } from 'react'
import { createPortal } from 'react-dom'
import { analytics, assertDay, FIRST_DAY, goalFor, hourlyFor, shiftDay, utcDay, type Entry } from '../shared/model'
import { engine, type AppState } from './data/store'
import Chart from './components/Chart'
import PeriodSummary from './components/PeriodSummary'
import RemainingProgress from './components/RemainingProgress'
import { headerDate, longDate, shortDate } from './utils/format'
import { draftFor } from './utils/drafts'
import { copyPopoutStyles, openCompactPopout, pictureInPicture } from './utils/popout'
import EntryForm, { type EntryDraft } from './components/EntryForm'
import DayCountForm, {type DayDraft} from './components/DayCountForm'
import GoalForm, { type GoalDraft } from './components/GoalForm'
import LoginForm from './components/LoginForm'
import Settings from './components/Settings'
import Modal from './components/Modal'
import Icon from './components/Icon'
import { registerPwa, type InstallEvent } from './pwa'

type DialogState={type:'entry';draft:EntryDraft}|{type:'day';draft:DayDraft}|{type:'goal';draft:GoalDraft}|{type:'settings'}|{type:'login'}|{type:'delete';entry:Entry}|null
const number=(n:number)=>n.toLocaleString('en')
function currentMode(){if(location.pathname==='/compact')return 'compact';try{return localStorage.getItem('vigil.mode.v1')==='compact'?'compact':'full'}catch{return 'full'}}
function initialSelected(){const day=new URL(location.href).searchParams.get('day');try{if(day)assertDay(day,utcDay());return day}catch{return null}}
function entryLabel(e:Entry){return e.easy&&e.external?`Easy ${number(e.easy)} + External ${number(e.external)}`:e.easy?'LinkedIn Easy Apply':'External / form'}
function EntryDescription({entry:e}:{entry:Entry}){return e.easy&&e.external?<><span className="easy-text">Easy {number(e.easy)}</span> + <span className="external-text">External {number(e.external)}</span></>:<span className={e.easy?'easy-text':'external-text'}>{entryLabel(e)}</span>}
function syncLabel(state:AppState){const n=state.queue.length;switch(state.status){case 'loading':return 'Loading…';case 'saving':return `Saving${n?' · '+n+' pending':''}`;case 'saved':return 'Saved';case 'offline':return `Offline · ${n?n+' pending':'cached'}`;case 'auth':return `Sign in to sync${n?' · '+n+' pending':''}`;case 'retry':return `Retry needed${n?' · '+n+' pending':''}`}}
function Brand({showMark=true}:{showMark?:boolean}){return <div className="brand">{showMark&&<img src="/mark.svg" alt=""/>}<span>Vigil</span></div>}
export default function Dashboard({floating=false,onOpenDashboard}:{floating?:boolean;onOpenDashboard?:()=>void}={}){
  const state=useSyncExternalStore(engine.subscribe,engine.getState)
  const [today,setToday]=useState(utcDay),[mode,setMode]=useState(currentMode),[range,setRange]=useState<7|15|30>(7),[selected,setSelected]=useState(initialSelected),[dialog,setDialog]=useState<DialogState>(null),[toast,setToast]=useState<{message:string;entryId?:string}|null>(null),[visibleCount,setVisibleCount]=useState(10),[install,setInstall]=useState<InstallEvent|null>(null),[update,setUpdate]=useState<ServiceWorker|null>(null),[nav,setNav]=useState('today')
  const [floatingWindow,setFloatingWindow]=useState<Window|null>(null),[openingFloat,setOpeningFloat]=useState(false)
  const openingRef=useRef(false)
  const topRef=useRef<HTMLElement>(null),historyRef=useRef<HTMLElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null),deleteGuard=useRef(false),popoutRef=useRef<Window|null>(null)
  useEffect(()=>{
    void engine.init()
    const day=()=>setToday(utcDay()),timer=setInterval(day,1000),focus=()=>{day();void engine.sync()},onInstall=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)}
    if(floating)return()=>clearInterval(timer)
    window.addEventListener('focus',focus);window.addEventListener('beforeinstallprompt',onInstall)
    void registerPwa(setUpdate).catch(()=>{/* The website remains usable if service workers are unavailable. */})
    return()=>{clearInterval(timer);window.removeEventListener('focus',focus);window.removeEventListener('beforeinstallprompt',onInstall)}
  },[floating])
  useEffect(()=>()=>{popoutRef.current?.close()},[])
  useEffect(()=>{if(floating)return;const handler=()=>{setMode(currentMode());setSelected(initialSelected())};window.addEventListener('popstate',handler);return()=>window.removeEventListener('popstate',handler)},[floating])
  function notify(message:string,entryId?:string){if(toastTimer.current)clearTimeout(toastTimer.current);if(message){setToast({message,entryId});toastTimer.current=setTimeout(()=>setToast(null),7000)}}
  async function popOut(){
    if(openingRef.current)return
    if(popoutRef.current&&!popoutRef.current.closed){popoutRef.current.focus();return}
    openingRef.current=true;setOpeningFloat(true)
    let popup:Window|null=null
    try{
      popup=await openCompactPopout(pictureInPicture())
      if(popup.closed)return
      copyPopoutStyles(document,popup.document)
      const opened=popup
      opened.addEventListener('pagehide',()=>{
        if(popoutRef.current===opened){popoutRef.current=null;setFloatingWindow(null)}
      },{once:true})
      popoutRef.current=opened;setFloatingWindow(opened)
    }catch(e){
      popup?.close()
      notify(pictureInPicture()?'The floating window could not open. Click the button again in desktop Chrome.':e instanceof Error?e.message:'Open Vigil directly in desktop Chrome to use floating view.')
    }finally{openingRef.current=false;setOpeningFloat(false)}
  }
  function changeMode(next:'full'|'compact'){setMode(next);try{localStorage.setItem('vigil.mode.v1',next)}catch{/* The route still preserves compact mode. */}history.pushState({},'',`${next==='compact'?'/compact':'/'}${selected?'?day='+selected:''}`)}
  function chooseDay(day:string|null){if(day){try{assertDay(day,utcDay())}catch{return}}setSelected(day);setVisibleCount(10);const url=new URL(location.href);if(day)url.searchParams.set('day',day);else url.searchParams.delete('day');history.replaceState({},'',url.pathname+url.search)}
  function custom(category:EntryDraft['category']){setDialog({type:'entry',draft:{kind:'entry',category,date:utcDay(),easy:category==='external'?'0':'1',external:category==='external'?'1':'0'}})}
  function editGoal(date=today){if(state.snapshot)setDialog({type:'goal',draft:{kind:'goal',date,value:String(goalFor(state.snapshot,date)),future:date===utcDay(),revision:state.snapshot.goalRevision}})}
  async function add(category:'easy'|'external',n:number){setToday(utcDay());try{const op=await engine.createEntry(category==='easy'?n:0,category==='external'?n:0);if(op?.type==='create')notify(`Added ${n} ${category==='easy'?'Easy Apply':'External / form'} application${n>1?'s':''}.`,op.entry.id)}catch(e){notify(e instanceof Error?e.message:'This entry could not be retained.')}}
  async function undo(entry:Entry|undefined){if(!entry)return;if(entry.date<utcDay()){setDialog({type:'delete',entry});return}try{const op=await engine.deleteEntry(entry.id,entry.version);if(op)notify(`Undid ${number(entry.easy+entry.external)} · ${entryLabel(entry)}.`)}catch(e){notify(e instanceof Error?e.message:'Undo could not be retained.')}}
  async function reapplyConflict(record:AppState['queue'][number]){
    const op=record.operation,cloud=state.snapshot?.entries.find(e=>'entryId'in op&&e.id===op.entryId&&!e.deleted)
    if((op.type==='update'||op.type==='delete')&&cloud&&(cloud.date<utcDay()||(op.type==='update'&&op.date<utcDay()))){
      try{await engine.resolveConflict(op.id,'cloud');setDialog(op.type==='delete'?{type:'delete',entry:cloud}:{type:'entry',draft:{...draftFor(cloud),easy:String(op.easy),external:String(op.external),date:op.date}})}catch(e){notify(e instanceof Error?e.message:'Reopen this entry to review its latest value.')}
    }else void engine.resolveConflict(op.id,'mine').catch(e=>notify(e.message))
  }
  const s=state.snapshot,compact=floating||mode==='compact',popout=floating
  if(!s)return <main className="page login-page"><div className="login-shell"><Brand/><h1>Your daily watch</h1>{state.status==='auth'?<LoginForm onDone={()=>notify('Welcome to Vigil.')}/>:<div className="loading-workspace"><p>{state.error??'Loading your private workspace…'}</p>{state.status==='retry'&&<button onClick={()=>{void engine.sync()}}>Retry</button>}</div>}<footer>Personal application tracker · UTC</footer></div></main>
  const a=analytics(s,range,today),totals=s.entries.filter(e=>!e.deleted),todayEasy=totals.filter(e=>e.date===today).reduce((n,e)=>n+e.easy,0),todayExternal=a.total-todayEasy,last=[...totals].sort((a,b)=>b.loggedAt.localeCompare(a.loggedAt)||b.id.localeCompare(a.id))[0],day=selected??today,hours=hourlyFor(s,day),recent=[...totals].filter(e=>!selected||e.date===selected).sort((a,b)=>b.loggedAt.localeCompare(a.loggedAt)||b.id.localeCompare(a.id)),pendingIds=new Set(state.queue.flatMap(q=>q.operation.type==='day'?[q.operation.additionId,...q.operation.expected.map(e=>e.id)]:q.operation.type==='create'?[q.operation.entry.id]:'entryId'in q.operation?[q.operation.entryId]:[])),conflict=state.queue.find(q=>q.status==='conflict'||q.status==='invalid')
  const selectedTotals=totals.filter(e=>e.date===day).reduce((sum,e)=>({easy:sum.easy+e.easy,external:sum.external+e.external}),{easy:0,external:0})
  function editDayCounts(){setDialog({type:'day',draft:{kind:'day',date:day,easy:String(selectedTotals.easy),external:String(selectedTotals.external),expected:totals.filter(e=>e.date===day).map(({id,version,easy,external,loggedAt})=>({id,version,easy,external,loggedAt}))}})}
  function close(){if(dialog?.type==='entry'||dialog?.type==='day'||dialog?.type==='goal')void engine.clearDraft();setDialog(null)}
  function finish(message:string,entryId?:string){setDialog(null);notify(message,entryId)}
  function scroll(which:'today'|'history'){setNav(which);const target=which==='today'?topRef:historyRef;target.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'})}
  return <><main className={`page${compact?' compact-page':''}${popout?' popout-page':''}`}>
    <div className={`shell${compact?' compact-shell':''}`}>
      {!compact&&<nav className="rail" aria-label="Main navigation"><img className="rail-brand-mark" src="/mark.svg" alt="" aria-hidden="true"/><button className={nav==='today'?'on':''} aria-label="Today" aria-current={nav==='today'?'page':undefined} onClick={()=>scroll('today')}><Icon name="today" size={17*1.25}/></button><button className={nav==='history'?'on':''} aria-label="History" aria-current={nav==='history'?'page':undefined} onClick={()=>scroll('history')}><Icon name="history" size={17*1.25}/></button><div className="rail-spacer"/><button aria-label="Settings" onClick={()=>setDialog({type:'settings'})}><Icon name="settings" size={20*1.25}/></button></nav>}
      <div className="workspace">
        <header className="header"><div className="header-identity"><Brand showMark={compact}/><time className="utc-date" dateTime={today} title={`${longDate(today)} · UTC`} aria-label={`${headerDate(today)} · UTC`}>{headerDate(today)}</time></div><div className="header-spacer"/><button className={`sync-status ${state.status}`} onClick={()=>state.status==='auth'?setDialog({type:'login'}):void engine.sync()} aria-label={`${syncLabel(state)}. ${state.status==='saved'?'Refresh cloud data':'Retry sync'}`}><i/>{syncLabel(state)}</button><button className="icon-button mode-button" aria-label={compact?'Open dashboard':'Open compact view'} title={compact?'Open dashboard':'Compact view'} onClick={()=>changeMode(compact?'full':'compact')}><Icon name={compact?'expand':'compact'}/></button>{!popout&&<button className="icon-button popout-button" aria-label="Pop out compact view" aria-pressed={!!floatingWindow} title={floatingWindow?"Focus floating view":"Always-on-top floating view"} disabled={openingFloat} onClick={()=>{void popOut()}}><Icon name="popout"/></button>}<button className="icon-button header-settings" aria-label="Open settings" title="Settings" onClick={()=>setDialog({type:'settings'})}><Icon name="settings" size={20}/></button></header>
        {state.error&&!conflict&&<div className="connection-note" role="status">{state.error} <button onClick={()=>{void engine.sync()}}>Retry</button></div>}
        {update&&<div className="update-note">An update is ready. <button disabled={state.queue.length>0||!!state.draft||!!dialog} onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});update.postMessage({type:'ACTIVATE'})}}>Update Vigil</button>{(state.queue.length>0||!!state.draft)&&<span>Finish your entry and sync first.</span>}</div>}
        {!!state.draft&&!dialog&&<div className="draft-note">You have a retained draft.<button onClick={()=>{const d=state.draft as EntryDraft|DayDraft|GoalDraft;setDialog(d.kind==='entry'?{type:'entry',draft:d}:d.kind==='day'?{type:'day',draft:d}:{type:'goal',draft:d})}}>Resume draft</button></div>}
        <section className="section summary" ref={topRef} aria-label="Today's applications"><div className="section-heading"><h1>{compact?'Applications today':'Today'}</h1><button className="text-button goal-edit" onClick={()=>editGoal()}><Icon name="edit" size={14}/>Edit goal</button></div><div className="metric-line"><div className="metric" data-testid="daily-count">{number(a.total)}</div><button className="goal-value" onClick={()=>editGoal()}>of <strong>{number(a.goal)}</strong> goal</button>{!compact&&<div className="remaining-top"><strong>{number(a.remaining)}</strong><span>remaining</span></div>}</div><RemainingProgress remaining={a.remaining} goal={a.goal}/></section>
        <section className="section logging" aria-label="Log applications"><div className="section-heading">{!compact&&<h2>Log applications <span>{selected&&selected!==today?'Today · '+shortDate(today)+' UTC':''}</span></h2>}{!compact&&<button className="small-button" onClick={()=>custom('mixed')}>Mixed batch</button>}</div>{(['easy','external'] as const).map(category=><div className={`quick-row ${category}`} key={category}><div className="category-heading"><span className="category-label"><i/>{category==='easy'?'LinkedIn Easy Apply':'External / form'}</span><strong className="category-count">{number(category==='easy'?todayEasy:todayExternal)}</strong></div><div className="quick-actions">{[1,2,3,5].map(n=><button className="increment" key={n} onClick={()=>{void add(category,n)}} aria-label={`Add ${n} ${category==='easy'?'LinkedIn Easy Apply':'External / form'} applications`}>+{n}</button>)}<button className="custom-button" onClick={()=>custom(category)}>Custom</button></div></div>)}</section>
        {compact?<footer className="compact-footer"><button disabled={!last} onClick={()=>{void undo(last)}} title={last?`Undo ${number(last.easy+last.external)} · ${entryLabel(last)}`:undefined}><Icon name="undo"/>Undo latest entry</button><button onClick={()=>floating?onOpenDashboard?.():changeMode('full')}>Open dashboard<Icon name="arrow"/></button></footer>:<>
          <section className="section day-history" ref={historyRef} aria-label="Browse UTC history"><div className="section-heading"><h2>Browse history</h2><button className="text-button" onClick={()=>chooseDay(null)}>Today</button></div><div className="day-navigation"><button aria-label="Previous UTC day" disabled={day<=FIRST_DAY} onClick={()=>chooseDay(shiftDay(day,-1))}>‹</button><label>UTC date<input aria-label="History UTC date" type="date" min={FIRST_DAY} max={today} value={day} onInput={e=>chooseDay(e.currentTarget.value)} onChange={e=>chooseDay(e.target.value)}/></label><button aria-label="Next UTC day" disabled={day>=today} onClick={()=>chooseDay(shiftDay(day,1))}>›</button></div><div className="selected-day-summary"><div><strong>{number(selectedTotals.easy+selectedTotals.external)}</strong><span>applications · {headerDate(day)}</span></div><span className="selected-day-categories"><i className="easy-dot"/><span><span className="selected-category-count">{number(selectedTotals.easy)}</span> Easy Apply</span><i className="external-dot"/><span><span className="selected-category-count">{number(selectedTotals.external)}</span> External / form</span></span><button className="small-button" onClick={editDayCounts}>Edit day counts</button></div>{day<today&&<p className="fine-print">Changes to this past UTC day require confirmation. Quick-entry buttons above always log today.</p>}</section>
          <section className="section history-chart"><div className="section-heading"><h2>Daily applications</h2><div className="segmented" role="group" aria-label="History range">{([7,15,30] as const).map(n=><button key={n} className={range===n?'selected':''} aria-pressed={range===n} onClick={()=>setRange(n)}>{n} days</button>)}</div></div><div className="legend"><span><i className="easy-dot"/>Easy Apply</span><span><i className="external-dot"/>External / form</span><span className="legend-hint">UTC days</span></div><Chart series={a.series} selected={selected} onSelect={chooseDay}/><PeriodSummary key={today} snapshot={s}/><div className="statistics period-goal-stats"><div><strong>{a.closedAverage===null?'—':a.closedAverage.toFixed(1)}</strong><span>Closed-day average</span></div><div><strong>{a.streak} <small>{a.streak===1?'day':'days'}</small></strong><span>Goal streak</span></div></div></section>
          <section className="section hourly"><div className="section-heading"><h2>Logged by hour <span>UTC · {shortDate(day)}</span></h2>{selected&&<button className="text-button" onClick={()=>chooseDay(null)}>Back to today</button>}</div><div className="hour-bars" role="img" aria-label={`Applications logged by UTC hour on ${day}: ${hours.hours.map((n,i)=>`${i}:00 ${n}`).join(', ')}`}>{hours.hours.map((n,i)=><div key={i} title={`${i.toString().padStart(2,'0')}:00 UTC · ${n} applications`}><i style={{height:n?`${n/Math.max(1,...hours.hours)*100}%`:'0'}}/></div>)}</div><div className="hour-axis"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div><p className="fine-print">When you logged, not when you submitted.{hours.backdated>0&&` Includes ${hours.backdated} applications assigned to an earlier date.`}{hours.otherDates>0&&` ${hours.otherDates} applications assigned to this day were logged on other dates.`}</p></section>
          <section className="section recent"><div className="section-heading"><h2>{selected?'Entries · '+shortDate(selected):'Recent entries'}</h2><button className="small-button" disabled={!last} onClick={()=>{void undo(last)}} title={last?`Undo ${number(last.easy+last.external)} · ${entryLabel(last)}`:undefined}><Icon name="undo"/>Undo latest entry</button></div><div className="history-tools"><label>Show UTC day<input type="date" min={FIRST_DAY} max={today} value={selected??''} onInput={e=>{if(e.currentTarget.value)chooseDay(e.currentTarget.value);else chooseDay(null)}} onChange={e=>{if(e.target.value)chooseDay(e.target.value);else chooseDay(null)}}/></label>{selected?<><button className="text-button" onClick={()=>chooseDay(null)}>All recent entries</button><button className="text-button" onClick={()=>editGoal(selected)}>Edit day goal · {goalFor(s,selected)}</button></>:<span>{totals.length} active {totals.length===1?'entry':'entries'}</span>}</div>{recent.length===0?<div className="empty-state">No applications {selected?'assigned to this UTC day':'logged yet'}.<p>Use the quick buttons above to begin.</p></div>:<div className="entry-list">{recent.slice(0,visibleCount).map(e=><div className="entry-row" key={e.id}><div className="entry-time"><time dateTime={e.loggedAt} title={`${e.loggedAt} · logged in UTC`}>{new Date(e.loggedAt).toLocaleTimeString('en-GB',{timeZone:'UTC',hour:'2-digit',minute:'2-digit'})} UTC</time><span>{shortDate(e.date)}{e.backdated?' · backdated':''}</span></div><div className="entry-detail"><span><EntryDescription entry={e}/></span><small>{pendingIds.has(e.id)?'Pending':e.version>1?'Edited':''}</small></div><strong className={e.easy&&!e.external?'easy-text':!e.easy?'external-text':''}>+{number(e.easy+e.external)}</strong><div className="entry-actions"><button className="text-button" onClick={()=>setDialog({type:'entry',draft:draftFor(e)})} aria-label={`Edit ${entryLabel(e)} entry at ${e.loggedAt}`}>Edit</button><button className="text-button delete-button" onClick={()=>setDialog({type:'delete',entry:e})} aria-label={`Delete ${entryLabel(e)} entry at ${e.loggedAt}`}>Delete</button></div></div>)}</div>}{recent.length>visibleCount&&<button className="load-more" onClick={()=>setVisibleCount(n=>n+10)}>Load 10 more entries</button>}</section>
        </>}
        {!compact&&<footer className="app-footer"><span>Vigil · Personal application tracker</span><span>Tracking since {shortDate(s.trackingStart)} · UTC</span></footer>}
      </div>
    </div>
    {conflict&&<div className="conflict-note" role="alert"><strong>Review a pending change</strong><p>{conflict.error}</p>{conflict.operation.type==='day'&&<p>Keep the cloud value, then reopen {conflict.operation.date} UTC and review its latest totals before trying again.</p>}{conflict.cloudEntry&&<p>Cloud: {entryLabel(conflict.cloudEntry)} · {number(conflict.cloudEntry.easy+conflict.cloudEntry.external)} on {conflict.cloudEntry.date}{conflict.cloudEntry.deleted?' (deleted)':''}.</p>}{conflict.operation.type==='goal'&&<p>Goal on {conflict.operation.date} UTC: cloud {number(conflict.cloudGoal??goalFor(s,conflict.operation.date))}; your change {number(conflict.operation.value)}{conflict.operation.future?' (also for future days)':''}.</p>}<div><button onClick={()=>{void engine.resolveConflict(conflict.operation.id,'cloud').catch(e=>notify(e.message))}}>Keep cloud value</button>{conflict.status==='conflict'&&conflict.operation.type!=='create'&&conflict.operation.type!=='import'&&conflict.operation.type!=='day'&&<button onClick={()=>{void reapplyConflict(conflict)}}>Apply my change</button>}</div></div>}
    {toast&&<div className="toast" role="status"><span>{toast.message}</span>{toast.entryId&&<button onClick={()=>{const e=state.snapshot?.entries.find(e=>e.id===toast.entryId&&!e.deleted);void undo(e);setToast(null)}}>Undo</button>}<button className="toast-close" aria-label="Dismiss message" onClick={()=>setToast(null)}><Icon name="close" size={14}/></button></div>}
    {dialog&&<Modal title={dialog.type==='entry'?(dialog.draft.entryId?'Edit application entry':dialog.draft.category==='mixed'?'Mixed batch':'Custom application count'):dialog.type==='day'?'Edit day counts · '+dialog.draft.date+' UTC':dialog.type==='goal'?'Daily goal':dialog.type==='settings'?'Settings':dialog.type==='login'?'Owner sign-in':dialog.entry.date<utcDay()?'Confirm past-day decrease':'Delete this entry?'} onClose={close}>
      {dialog.type==='day'&&<DayCountForm draft={dialog.draft} onDone={finish}/>}
      {dialog.type==='entry'&&<EntryForm draft={dialog.draft} onDone={finish}/>}{dialog.type==='goal'&&<GoalForm draft={dialog.draft} onDone={()=>finish('Goal retained.')}/>}{dialog.type==='settings'&&<Settings state={state} install={install} onDone={finish} onLogin={()=>setDialog({type:'login'})}/>}{dialog.type==='login'&&<LoginForm onDone={()=>finish('Signed in. Syncing retained changes.')}/>}
      {dialog.type==='delete'&&<><p className="form-note">Remove {number(dialog.entry.easy+dialog.entry.external)} applications from {dialog.entry.date} UTC?<br/>{entryLabel(dialog.entry)}</p><p className="fine-print">The entry is marked deleted and excluded from totals.</p>{dialog.entry.date<utcDay()&&<div className="delete-review"><strong>Double-check {dialog.entry.date} UTC</strong><p>Easy Apply: {number(totals.filter(e=>e.date===dialog.entry.date).reduce((n,e)=>n+e.easy,0))} → {number(totals.filter(e=>e.date===dialog.entry.date&&e.id!==dialog.entry.id).reduce((n,e)=>n+e.easy,0))}</p><p>External / form: {number(totals.filter(e=>e.date===dialog.entry.date).reduce((n,e)=>n+e.external,0))} → {number(totals.filter(e=>e.date===dialog.entry.date&&e.id!==dialog.entry.id).reduce((n,e)=>n+e.external,0))}</p></div>}<div className="form-actions"><button onClick={close}>Cancel</button><button className="danger-button" onClick={()=>{if(deleteGuard.current)return;deleteGuard.current=true;void engine.deleteEntry(dialog.entry.id,dialog.entry.version).then(()=>finish('Entry deleted.')).catch(e=>notify(e.message)).finally(()=>{deleteGuard.current=false})}}>Delete entry</button></div></>}
    </Modal>}
  </main>{!floating&&floatingWindow&&createPortal(<Dashboard floating onOpenDashboard={()=>{changeMode('full');window.focus()}}/>,floatingWindow.document.body)}</>
}
